-- Generated by scripts/cuda_profile.py from profile.json.
module Markovian.Backend.GPU.Artifact where

profileSHA256 :: String
profileSHA256 = "150e39b7844d270cd145851327f8fcb1cd6681149ed882c47b56bb43ab9f45f2"

ptxTarget :: String
ptxTarget = "sm_121"

ptxISAVersion :: String
ptxISAVersion = "9.0"

kernelName :: String
kernelName = "markovian_f64_matmul"

kernelABI :: String
kernelABI = "markovian-f64-matmul-v1"

ptxSHA256 :: String
ptxSHA256 = "a01d2c898a78dc4f603a8919c9f84019b79066201bc12430fedc725ac97f6239"

requiredCapabilityMajor :: Integer
requiredCapabilityMajor = 12

requiredCapabilityMinor :: Integer
requiredCapabilityMinor = 1

requiredThreadsPerBlock :: Integer
requiredThreadsPerBlock = 128

ptxLength :: Integer
ptxLength = 5251
