-- Generated by scripts/build-ptx from cbits/markovian_dense.ptx.
module Markovian.Backend.GPU.Artifact where

ptxTarget :: String
ptxTarget = "sm_121"

kernelName :: String
kernelName = "markovian_f64_matmul"

kernelABI :: String
kernelABI = "markovian-f64-matmul-v1"

ptxSHA256 :: String
ptxSHA256 = "a01d2c898a78dc4f603a8919c9f84019b79066201bc12430fedc725ac97f6239"

ptxLength :: Integer
ptxLength = 5251
